name: tarsier_local_storage
description: A simple and flexible library for managing SQLite databases in Dart and Flutter applications.
version: 1.0.1
homepage: https://github.com/marianz-bonfire/tarsier_local_storage
repository: https://github.com/marianz-bonfire/tarsier_local_storage
issue_tracker: https://github.com/marianz-bonfire/tarsier_local_storage/issues

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  windows:
  linux:

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5

screenshots:
  - description: The package logo.
    path: assets/logo.png