/// Abstract class representing the base model for database tables.
///
/// This class provides a contract for converting models to a key-value map
/// and accessing properties dynamically. It is intended to be extended
/// by concrete implementations that define specific models.
///
/// ## Usage
/// ```dart
/// class User extends BaseTableModel {
///   final int id;
///   final String username;
///   final String password;
///
///   User({required this.id, required this.username, required this.password});
///
///   @override
///   Map<String, dynamic> toMap() {
///     return {
///       'id': id,
///       'username': username,
///       'password': password,
///     };
///   }
/// }
/// ```
abstract class BaseTableModel {
  /// Converts the model to a map of key-value pairs.
  ///
  /// This method is used to serialize the model into a format compatible
  /// with database operations. Each concrete implementation must define
  /// how the model is converted into a map.
  ///
  /// Returns a [Map<String, dynamic>] representing the model.
  Map<String, dynamic> toMap();

  /// Retrieves a property value from the model by its name.
  ///
  /// This method allows dynamic access to the model's properties by name,
  /// leveraging the map generated by [toMap].
  ///
  /// - [propertyName]: The name of the property to retrieve.
  ///
  /// Throws an [ArgumentError] if the specified property is not found.
  ///
  /// Returns the value of the property if it exists.
  dynamic get(String propertyName) {
    var map = toMap();
    if (map.containsKey(propertyName)) {
      return map[propertyName];
    }
    throw ArgumentError('Property "$propertyName" not found');
  }
}
